name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint

      - name: Zip build folder
        run: zip -r ${{ github.repository }}-v${{ steps.package-json-endpoint.outputs.endpoint }}.zip build

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ steps.package-json-endpoint.outputs.endpoint }}
          release_name: Release v${{ steps.package-json-endpoint.outputs.endpoint }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.repository }}-v${{ steps.package-json-endpoint.outputs.endpoint }}.zip
          asset_name: ${{ github.repository }}-v${{ steps.package-json-endpoint.outputs.endpoint }}.zip
          asset_content_type: application/zip
