name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Zip build folder
        run: zip -r ${{ github.repository }}-v${{ github.package-json.version }}.zip build

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ github.package-json.version }}
          release_name: Release v${{ github.package-json.version }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.repository }}-v${{ github.package-json.version }}.zip
          asset_name: ${{ github.repository }}-v${{ github.package-json.version }}.zip
          asset_content_type: application/zip
